name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm ci
      run: |
        npm ci
        npm test
        npm run eslint
      env:
        CI: true
    - name: Unit test
      run: |
        npm test
        npm run eslint
      env:
        CI: true
    - name: Code quality
      run: |
        npm run eslint
      env:
        CI: true
        
