name: 'eslint-config-google'

on:
  push:
    branches:
      - master
      - development
      - 'feature/cli'

jobs:
  build:
    name: Stub-backend

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 8.x , 10.x , 12.x ]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Code quality
      run: |
        npm run eslint
      env:
        CI: true
        
